apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: proyecto2
data:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
    - name: Redis
      type: redis-datasource
      url: redis:6379
      editable: true
      isDefault: true
    - name: Valkey
      type: redis-datasource
      url: valkey:6379
      editable: true
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: proyecto2
spec:
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: proyecto2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
        env:
        - name: GF_INSTALL_PLUGINS
          value: redis-datasource
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
      volumes:
      - name: grafana-datasources
        configMap:
          name: grafana-datasources