apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: proyecto2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: "admin"
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin"
        - name: GF_INSTALL_PLUGINS
          value: "redis-datasource"
        resources:
          limits:
            memory: "512Mi"
            cpu: "300m"
          requests:
            memory: "256Mi"
            cpu: "100m"
        volumeMounts:
        - name: grafana-config
          mountPath: /etc/grafana/provisioning/datasources
      volumes:
      - name: grafana-config
        configMap:
          name: grafana-datasources
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: proyecto2
spec:
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: proyecto2
data:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
      - name: Redis
        type: redis-datasource
        access: proxy
        url: redis:6379
        editable: true
      - name: Valkey
        type: redis-datasource
        access: proxy
        url: valkey:6379
        editable: true